const CR = 1e7; // 1 crore in rupees

function wikimediaImg(filename, width) {
  return "https://commons.wikimedia.org/wiki/Special:FilePath/" + encodeURIComponent(filename) + "?width=" + width;
}

// Real, sourced corruption/waste cases (unchanged from earlier research) —
// each keeps its evidence-type label + source link behind the small "i" icon
// next to the loss figure, so the exact-replica UI doesn't lose that rigor.
const CASES = [
  {
    id: "2g",
    icon: "📡",
    name: "2G Spectrum Scam (2008)",
    amount: 176000 * CR,
    usdApprox: "$24 billion",
    statusLabel: "CAG-estimated presumptive loss — later acquitted (2017)",
    source: "https://en.wikipedia.org/wiki/2G_spectrum_case",
  },
  {
    id: "coal",
    icon: "⛏️",
    name: "Coal Block Allocations (2012)",
    amount: 186000 * CR,
    usdApprox: "$25 billion",
    statusLabel: "CAG-estimated loss",
    source: "https://en.wikipedia.org/wiki/Coal_allocation_scam",
  },
  {
    id: "fodder",
    icon: "🐄",
    name: "Fodder Scam (Bihar)",
    amount: 39.59 * CR,
    usdApprox: "$4.8 million",
    statusLabel: "Convicted",
    source: "https://en.wikipedia.org/wiki/Fodder_scam",
  },
  {
    id: "da-case",
    icon: "⚖️",
    name: "Disproportionate Assets Case (1996)",
    amount: 100 * CR,
    usdApprox: "$12 million",
    statusLabel: "Convicted — court-imposed fine",
    source: "https://en.wikipedia.org/wiki/Disproportionate_assets_case_against_J._Jayalalithaa",
  },
  {
    id: "central-vista",
    icon: "🏛️",
    name: "Central Vista Redevelopment",
    amount: 13169.61 * CR,
    usdApprox: "$1.6 billion",
    statusLabel: "Disclosed cost — CAG flagged pricing 64% above market",
    source: "https://en.wikipedia.org/wiki/Central_Vista_Redevelopment_Project",
  },
  {
    id: "pm-trips",
    icon: "✈️",
    name: "PM's Foreign Visits (2022–24)",
    amount: 258.9 * CR,
    usdApprox: "$31 million",
    statusLabel: "Disclosed expenditure — no wrongdoing alleged",
    source: "https://madhyamamonline.com/india/bjp-govt-spends-rs-2589-crore-of-taxpayers-money-on-pm-modis-foreign-visits-1391774",
  },
];

// The 12 build items, matching the reference design exactly (name, price,
// description). Photos are real, freely-licensed (CC) images from Wikimedia
// Commons matching each category — not extracted from any reference image.
const BUILD_ITEMS = [
  {
    id: "hospital",
    name: "Multi-speciality Hospital",
    cost: 500 * CR,
    costLabel: "₹500 Crore",
    desc: "A 1,000-bed hospital with advanced medical equipment.",
    img: wikimediaImg("Nagpur Government Medical College and Hospital.jpg", 700),
  },
  {
    id: "school",
    name: "Modern School",
    cost: 20 * CR,
    costLabel: "₹20 Crore",
    desc: "A high-quality school with smart classrooms for 1,000 students.",
    img: wikimediaImg("Tamil Nadu school kids.jpg", 700),
  },
  {
    id: "highway",
    name: "National Highway (100 km)",
    cost: 1000 * CR,
    costLabel: "₹1,000 Crore",
    desc: "Builds 100 km of 4-lane highway with modern facilities.",
    img: wikimediaImg("Drone view of a national highway in India.png", 700),
  },
  {
    id: "metro",
    name: "Metro Rail (10 km)",
    cost: 5000 * CR,
    costLabel: "₹5,000 Crore",
    desc: "10 km of metro rail including stations and infrastructure.",
    img: wikimediaImg("Delhi Metro train red line at Shaheed Sthal metro station.jpg", 700),
  },
  {
    id: "water",
    name: "Clean Drinking Water for 1 Lakh People",
    cost: 50 * CR,
    costLabel: "₹50 Crore",
    desc: "Complete water supply system with treatment and distribution.",
    img: wikimediaImg("Hand-operated water pump in Mahabalipuram.jpg", 700),
  },
  {
    id: "solar",
    name: "Renewable Energy Plant (500 MW)",
    cost: 2500 * CR,
    costLabel: "₹2,500 Crore",
    desc: "Solar plant powering ~10 lakh households with clean energy.",
    img: wikimediaImg("AMP Energy Bhadla Solar Power Plant - 53699816551.jpg", 700),
  },
  {
    id: "housing",
    name: "Rural Housing (1,000 homes)",
    cost: 300 * CR,
    costLabel: "₹300 Crore",
    desc: "1,000 pucca homes for rural families with basic amenities.",
    img: wikimediaImg("Rural india house in Maharashtra.jpg", 700),
  },
  {
    id: "phc",
    name: "Primary Health Centre",
    cost: 10 * CR,
    costLabel: "₹10 Crore",
    desc: "A fully equipped PHC serving 50,000 people.",
    img: wikimediaImg("Primary Health Centre, Kakching Khunou.jpg", 700),
  },
  {
    id: "college",
    name: "Government College",
    cost: 100 * CR,
    costLabel: "₹100 Crore",
    desc: "A modern college for 5,000 students with advanced facilities.",
    img: wikimediaImg("Government Law College ,Vellore.jpg", 700),
  },
  {
    id: "anganwadi",
    name: "Anganwadi Centre (100 centres)",
    cost: 25 * CR,
    costLabel: "₹25 Crore",
    desc: "100 centres for child nutrition, early education and care.",
    img: wikimediaImg("Nirappam kunnu Anganwadi Centre, Cheruvannur Grama Panchayat, Kozhikode.jpg", 700),
  },
  {
    id: "toilet",
    name: "Rural Sanitation (10,000 toilets)",
    cost: 100 * CR,
    costLabel: "₹100 Crore",
    desc: "10,000 household toilets for a cleaner and healthier India.",
    img: wikimediaImg("Temporary public toilets 2 (2731611990).jpg", 700),
  },
  {
    id: "computerlab",
    name: "Digital Learning Labs (1,000 schools)",
    cost: 200 * CR,
    costLabel: "₹200 Crore",
    desc: "Computer labs with internet access for 1,000 schools.",
    img: wikimediaImg("Computer Lab - SRMPS - Shri Ramswaroop Memorial Public School.jpg", 700),
  },
];

// Impact page: a fixed 8-category illustrative breakdown, defined at the
// reference amount below (matches the 2G case, ₹1,76,000 crore) and scaled
// proportionally for whichever case is actually selected — the reference
// design's own numbers don't derive from BUILD_ITEMS unit costs (100,000
// classrooms at ₹20cr each would be ₹20 lakh crore, far past any real case
// here), so they're a narrative illustration tied to that one amount, not a
// literal tally of per-unit prices. Scaling keeps it honest for smaller cases
// instead of showing impossible quantities.
const IMPACT_REFERENCE_AMOUNT = 176000 * CR;
const IMPACT_REFERENCE_PEOPLE_BENEFITED = 3.4 * CR;

const IMPACT_CATEGORIES = [
  {
    id: "education",
    badgeIcon: "📖",
    badgeLabel: "Education",
    qty: 100000,
    unitLabel: "Modern Classrooms",
    subLabel: "For {n} students",
    subN: 1 * CR,
    desc: "Well-equipped classrooms with smart boards, furniture and learning resources.",
    peopleBenefited: 1 * CR,
    peopleCaption: "Students get better education",
    img: wikimediaImg("Tamil Nadu school kids.jpg", 700),
  },
  {
    id: "healthcare",
    badgeIcon: "➕",
    badgeLabel: "Healthcare",
    qty: 400,
    unitLabel: "Multi-speciality Hospitals",
    subLabel: "For {n} people",
    subN: 2 * CR,
    desc: "Modern hospitals with advanced equipment, ICUs and trained medical staff.",
    peopleBenefited: 2 * CR,
    peopleCaption: "People get access to quality healthcare",
    img: wikimediaImg("Nagpur Government Medical College and Hospital.jpg", 700),
  },
  {
    id: "water",
    badgeIcon: "💧",
    badgeLabel: "Clean Water",
    qty: 2000,
    unitLabel: "Clean Water Projects",
    subLabel: "For {n} people",
    subN: 50 * 1e5,
    desc: "Safe drinking water systems with treatment plants and distribution networks.",
    peopleBenefited: 50 * 1e5,
    peopleCaption: "People get clean and safe drinking water",
    img: wikimediaImg("Hand-operated water pump in Mahabalipuram.jpg", 700),
  },
  {
    id: "infra",
    badgeIcon: "🏗️",
    badgeLabel: "Infrastructure",
    qty: 1000,
    unitLabel: "km National Highways",
    subLabel: "Better connectivity for millions",
    subN: null,
    desc: "Modern 4-lane highways with safety features, bridges and service facilities.",
    peopleBenefited: 1.5 * CR,
    peopleCaption: "People benefit from improved connectivity",
    img: wikimediaImg("Drone view of a national highway in India.png", 700),
  },
  {
    id: "transport",
    badgeIcon: "🚇",
    badgeLabel: "Public Transport",
    qty: 10,
    unitLabel: "km Metro Rail",
    subLabel: "For {n} daily commuters",
    subN: 10 * 1e5,
    desc: "Modern metro rail with stations and basic infrastructure.",
    peopleBenefited: 10 * 1e5,
    peopleCaption: "Daily commuters get faster, safer travel",
    img: wikimediaImg("Delhi Metro train red line at Shaheed Sthal metro station.jpg", 700),
  },
  {
    id: "housing",
    badgeIcon: "🏠",
    badgeLabel: "Rural Development",
    qty: 1000,
    unitLabel: "Rural Homes",
    subLabel: "For {n} families",
    subN: 1000,
    desc: "Safe and durable homes with basic amenities like electricity, water and sanitation.",
    peopleBenefited: 5000,
    peopleCaption: "People get a safer place to live",
    img: wikimediaImg("Rural india house in Maharashtra.jpg", 700),
  },
  {
    id: "sanitation",
    badgeIcon: "🚽",
    badgeLabel: "Sanitation",
    qty: 10000,
    unitLabel: "Public Toilets",
    subLabel: "For cleaner, healthier communities",
    subN: null,
    desc: "Well-maintained toilets in rural and urban areas to improve hygiene and public health.",
    peopleBenefited: 50 * 1e5,
    peopleCaption: "People get access to proper sanitation",
    img: wikimediaImg("Temporary public toilets 2 (2731611990).jpg", 700),
  },
  {
    id: "digital",
    badgeIcon: "💻",
    badgeLabel: "Digital Education",
    qty: 1000,
    unitLabel: "Digital Learning Labs",
    subLabel: "For {n} students",
    subN: 10 * 1e5,
    desc: "Computer labs with internet access, devices and digital learning resources.",
    peopleBenefited: 10 * 1e5,
    peopleCaption: "Students gain digital skills for the future",
    img: wikimediaImg("Computer Lab - SRMPS - Shri Ramswaroop Memorial Public School.jpg", 700),
  },
];
